# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml -f compose.pc.husarnet.yaml up

version: "2.3"

services:

  mappers:
    network_mode: service:husarnet
    volumes:
      - ./secret/dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  rviz:
    network_mode: service:husarnet
    volumes: 
      - ./secret/dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  husarnet:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
      - ./secret/id_rviz:/var/lib/husarnet/id
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rviz
      - JOINCODE
