# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

version: "2.3"

services:

  # ROS Galactic
  mappers:
    image: mappers
    build: ../mapper-packages
    restart: unless-stopped
    tty: true
    volumes: 
      - /home/s/map:/map
      - /home/s/heatmaps:/heatmaps
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

  rviz:
    image: husarion/rviz2:galactic
    restart: on-failure
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_pro_mapping.rviz:/root/.rviz2/default.rviz
      # - ./config/rosbot_pro_localization.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
