# Quick Start
# $ docker compose -f compose.rosbot.yaml -f compose.rosbot.husarnet.yaml up

version: "2.3"

services:

  nav2:
    network_mode: service:husarnet
    volumes:
      - ./dds-config.xml:/dds-config.xml
    environment:
      - CYCLONEDDS_URI=file:///dds-config.xml

  bridge:
    network_mode: service:husarnet
    volumes:
      - ./dds-config.xml:/dds-config.xml 
    environment:
      - CYCLONEDDS_URI=file:///dds-config.xml

  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rosbot
      - JOINCODE=${HUSARNET_JOINCODE}

